language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t loico/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true loico/react-test npm run test

after_success:
  - docker build -t loico/multi-client ./client
  - docker build -t loico/multi-nginx ./nginx
  - docker build -t loico/multi-server ./server
  - docker build -t loico/multi-worker ./worker
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images an push them to docker hub
  - docker push loico/multi-client
  - docker push loico/multi-nginx
  - docker push loico/multi-server
  - docker push loico/multi-worker
